name: ASP.NET Core CI/CD

on:
  push:
    branches:
      - main  # or whatever your main branch is called
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'  # or the version you are using
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    - name: Publish
      run: dotnet publish -c Release -o ./publish
    
  deploy:
    runs-on: windows-latest
    needs: build
    
    steps:
    - name: Deploy to Windows server
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        server-dir: '/path/to/your/deployment/folder'
        local-dir: './publish'
