---
name: Build and deploy ASP.Net Core app to On-Premises Server - Git Actions
on:
  push:
    branches:
      - master
  workflow_dispatch: null
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Stop IIS app pool
        run: |
          $appPoolName = 'git-actions-poc'
          #Import-Module WebAdministration -Verbose
          Write-Output "Stopping IIS app pool $appPoolName"
          Stop-WebAppPool -Name $appPoolName
        shell: pwsh
      - uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: dotnet publish
        run: dotnet publish -c Release -o ${{ github.workspace }}/publish
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v2
        with:
          name: published-app
          path: ${{ github.workspace }}/publish
  run-inline-powershell:
    runs-on: windows-latest
    steps:
      - name: Start IIS app pool
        run: |
          $appPoolName = 'git-actions-poc'
          #Import-Module WebAdministration -Verbose
          Write-Output "Starting IIS app pool $appPoolName"
          Start-WebAppPool -Name $appPoolName
        shell: pwsh
