name: Build and deploy ASP.Net Core app to On-Premises Server - Git Actions

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x' # Adjust version as per your requirement  

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{ github.workspace }}/publish

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v2
        with:
          name: published-app
          path: ${{ github.workspace }}/publish
    
  deploy:
    runs-on: self-hosted
    needs: build
    
    steps:
    - name: Run PowerShell script
        shell:pwsh
        run:|
          .\deploy.ps1
